const Images = {
    LOGO_LAC_VIET: require('./logo-dau-gia-lac-viet.png'),
    BACKGROUND_PROFILE: require('./bgProfile.png'),
    SUCCESS_ICON: require('./SuccessIcon.png'),
    BUOI_SANG: require('./buoi-sang.png'),
    BUOI_CHIEU: require('./buoi-chieu.png'),
    BUOI_TOI: require('./buoi-toi.png'),
    ERROR_ICON: require('./ErrorIcon.png'),
    AVATAR_DEFAULT : require('./avatar-default.jpeg'),
    HEALTH_FACILITICES_BACKGROUND : require('./healthFacilitiesBackground.png'),
    BACKGROUND_HEADER: require('./backgroud-header.png'),
    BACKGROUND_HEADER_SHORT: require('./backgroud-header-short.png'),
    BACKGROUND_HEADER_LONG: require('./backgroud-header-long.png'),
    IMAGE_LOGIN: require('./image-login.png'),
    FACEBOOK_LOGIN: require('./facebook-logo.png'),
    GOOGLE_LOGIN: require('./google-logo.png'),
    APPLE_LOGIN: require('./apple-logo.png'),
    TOPIC_SERVEY: require('./topicServey.png'),
    Servey:require('./qualitativeResearch.png'),
    CIRCLE:require('./image-circle.png'),
    BACKGROUND_SERVEY_INFOR: require('./backgroud-servey-info.png'),
    BACKGROUND_HOME: require('./background-image-home.png'),
    BACKGROUND_HOME_1: require('./background-image-home1.png'),
    BACKGROUND_HOME_2: require('./background-home.png'),
    BACKGROUND_SURVEY: require('./background-survey.png'),
    FORUM: require('./forum.png'),
    CHAT_BOT: require('./chat-bot.png'),
};

export default Images;